-- Maritime Actionable Ontology Demo Kit
-- Relational source-of-record contract. Empty MARITIME_SS_* namespace only.

SET SERVEROUTPUT ON

DECLARE
  l_user          VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));
  l_schema        VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'));
  l_object_count  NUMBER;
BEGIN
  IF l_user <> 'MARITIME_DEMO' OR l_schema <> 'MARITIME_DEMO' THEN
    RAISE_APPLICATION_ERROR(
      -20000,
      'Safety stop: connect directly as MARITIME_DEMO.'
    );
  END IF;

  SELECT COUNT(*)
    INTO l_object_count
    FROM USER_OBJECTS
   WHERE OBJECT_NAME LIKE 'MARITIME\_SS\_%' ESCAPE '\';

  IF l_object_count <> 0 THEN
    RAISE_APPLICATION_ERROR(
      -20001,
      'MARITIME_SS_* namespace is not empty. Existing objects are never deleted automatically.'
    );
  END IF;
END;
/

CREATE TABLE MARITIME_DEMO.MARITIME_SS_DEMO_CLOCK (
  CLOCK_ID                 NUMBER(1),
  AS_OF_TS                 TIMESTAMP WITH TIME ZONE NOT NULL,
  TIMEZONE_REGION          VARCHAR2(64) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_CLOCK_PK PRIMARY KEY (CLOCK_ID),
  CONSTRAINT MARITIME_SS_CLOCK_SINGLETON_CK CHECK (CLOCK_ID = 1),
  CONSTRAINT MARITIME_SS_CLOCK_TZ_CK CHECK (TIMEZONE_REGION = 'UTC'),
  CONSTRAINT MARITIME_SS_CLOCK_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_POLICY_VERSIONS (
  POLICY_VERSION           VARCHAR2(40),
  ACTIVE_YN                CHAR(1) NOT NULL,
  EFFECTIVE_FROM_TS        TIMESTAMP WITH TIME ZONE NOT NULL,
  TIGHT_THRESHOLD_MIN      NUMBER(5) NOT NULL,
  MAX_INGEST_LAG_MIN       NUMBER(5) NOT NULL,
  APPROVAL_STATE           VARCHAR2(20) NOT NULL,
  EXTERNAL_EXECUTION_YN    CHAR(1) NOT NULL,
  POLICY_SUMMARY        VARCHAR2(1000) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_POLICY_PK PRIMARY KEY (POLICY_VERSION),
  CONSTRAINT MARITIME_SS_POLICY_ACTIVE_CK CHECK (ACTIVE_YN IN ('Y', 'N')),
  CONSTRAINT MARITIME_SS_POLICY_THRESHOLD_CK CHECK (TIGHT_THRESHOLD_MIN > 0),
  CONSTRAINT MARITIME_SS_POLICY_LAG_CK CHECK (MAX_INGEST_LAG_MIN >= 0),
  CONSTRAINT MARITIME_SS_POLICY_APPROVAL_CK CHECK (APPROVAL_STATE = 'PREVIEW_ONLY'),
  CONSTRAINT MARITIME_SS_POLICY_EXEC_CK CHECK (EXTERNAL_EXECUTION_YN = 'N'),
  CONSTRAINT MARITIME_SS_POLICY_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE UNIQUE INDEX MARITIME_DEMO.MARITIME_SS_POLICY_ONE_ACTIVE_UI
  ON MARITIME_DEMO.MARITIME_SS_POLICY_VERSIONS (
    CASE WHEN ACTIVE_YN = 'Y' THEN 1 END
  );

CREATE TABLE MARITIME_DEMO.MARITIME_SS_FIXTURE_MANIFEST (
  FIXTURE_VERSION          VARCHAR2(40),
  CONTRACT_VERSION         VARCHAR2(40) NOT NULL,
  ONTOLOGY_VERSION         VARCHAR2(40) NOT NULL,
  POLICY_VERSION           VARCHAR2(40) NOT NULL,
  SCENARIO_ID              VARCHAR2(30) NOT NULL,
  DATA_AS_OF_TS            TIMESTAMP WITH TIME ZONE NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CREATED_AT               TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT MARITIME_SS_MANIFEST_PK PRIMARY KEY (FIXTURE_VERSION),
  CONSTRAINT MARITIME_SS_MANIFEST_POLICY_FK
    FOREIGN KEY (POLICY_VERSION)
    REFERENCES MARITIME_DEMO.MARITIME_SS_POLICY_VERSIONS (POLICY_VERSION),
  CONSTRAINT MARITIME_SS_MANIFEST_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_VESSELS (
  VESSEL_ID                VARCHAR2(30),
  VESSEL_NAME              VARCHAR2(100) NOT NULL,
  IMO_NUMBER               VARCHAR2(20),
  VESSEL_STATUS            VARCHAR2(20) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_VESSEL_PK PRIMARY KEY (VESSEL_ID),
  CONSTRAINT MARITIME_SS_VESSEL_STATUS_CK
    CHECK (VESSEL_STATUS IN ('ACTIVE', 'CONTROL')),
  CONSTRAINT MARITIME_SS_VESSEL_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_VOYAGES (
  VOYAGE_ID                VARCHAR2(30),
  VOYAGE_NO                VARCHAR2(30) NOT NULL,
  VESSEL_ID                VARCHAR2(30) NOT NULL,
  VOYAGE_ROLE              VARCHAR2(20) NOT NULL,
  SERVICE_CODE             VARCHAR2(30) NOT NULL,
  VOYAGE_STATUS            VARCHAR2(20) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_VOYAGE_PK PRIMARY KEY (VOYAGE_ID),
  CONSTRAINT MARITIME_SS_VOYAGE_NO_UQ UNIQUE (VOYAGE_NO),
  CONSTRAINT MARITIME_SS_VOYAGE_VESSEL_FK
    FOREIGN KEY (VESSEL_ID) REFERENCES MARITIME_DEMO.MARITIME_SS_VESSELS (VESSEL_ID),
  CONSTRAINT MARITIME_SS_VOYAGE_ROLE_CK
    CHECK (VOYAGE_ROLE IN ('INBOUND', 'OUTBOUND', 'CONTROL')),
  CONSTRAINT MARITIME_SS_VOYAGE_STATUS_CK
    CHECK (VOYAGE_STATUS IN ('PLANNED', 'IN_PROGRESS', 'CONTROL')),
  CONSTRAINT MARITIME_SS_VOYAGE_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_PORTS (
  PORT_CODE                VARCHAR2(10),
  PORT_NAME             VARCHAR2(100) NOT NULL,
  COUNTRY_CODE             CHAR(2) NOT NULL,
  TIMEZONE_REGION          VARCHAR2(64) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_PORT_PK PRIMARY KEY (PORT_CODE),
  CONSTRAINT MARITIME_SS_PORT_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_PORT_CALLS (
  PORT_CALL_ID             VARCHAR2(30),
  VOYAGE_ID                VARCHAR2(30) NOT NULL,
  PORT_CODE                VARCHAR2(10) NOT NULL,
  TERMINAL_CODE            VARCHAR2(30) NOT NULL,
  PLANNED_ARRIVAL_AT       TIMESTAMP WITH TIME ZONE NOT NULL,
  PORT_CALL_STATUS         VARCHAR2(20) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_CALL_PK PRIMARY KEY (PORT_CALL_ID),
  CONSTRAINT MARITIME_SS_CALL_VOYAGE_FK
    FOREIGN KEY (VOYAGE_ID) REFERENCES MARITIME_DEMO.MARITIME_SS_VOYAGES (VOYAGE_ID),
  CONSTRAINT MARITIME_SS_CALL_PORT_FK
    FOREIGN KEY (PORT_CODE) REFERENCES MARITIME_DEMO.MARITIME_SS_PORTS (PORT_CODE),
  CONSTRAINT MARITIME_SS_CALL_VOYAGE_UQ UNIQUE (VOYAGE_ID, PORT_CALL_ID),
  CONSTRAINT MARITIME_SS_CALL_STATUS_CK
    CHECK (PORT_CALL_STATUS IN ('PLANNED', 'DELAY_REVIEW', 'CONTROL')),
  CONSTRAINT MARITIME_SS_CALL_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_ETA_EVENTS (
  ETA_EVENT_ID             VARCHAR2(40),
  PORT_CALL_ID             VARCHAR2(30) NOT NULL,
  REVISION_NO              NUMBER(8) NOT NULL,
  SOURCE_SYSTEM            VARCHAR2(40) NOT NULL,
  SOURCE_EVENT_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
  RECEIVED_AT              TIMESTAMP WITH TIME ZONE NOT NULL,
  REPORTED_ETA_AT          TIMESTAMP WITH TIME ZONE NOT NULL,
  PAYLOAD_STATUS           VARCHAR2(20) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_ETA_PK PRIMARY KEY (ETA_EVENT_ID),
  CONSTRAINT MARITIME_SS_ETA_CALL_FK
    FOREIGN KEY (PORT_CALL_ID) REFERENCES MARITIME_DEMO.MARITIME_SS_PORT_CALLS (PORT_CALL_ID),
  CONSTRAINT MARITIME_SS_ETA_REVISION_UQ UNIQUE (PORT_CALL_ID, REVISION_NO),
  CONSTRAINT MARITIME_SS_ETA_REVISION_CK CHECK (REVISION_NO >= 0),
  CONSTRAINT MARITIME_SS_ETA_STATUS_CK CHECK (PAYLOAD_STATUS IN ('ACCEPTED', 'CONTROL')),
  CONSTRAINT MARITIME_SS_ETA_RECEIPT_CK CHECK (RECEIVED_AT >= SOURCE_EVENT_AT),
  CONSTRAINT MARITIME_SS_ETA_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_TERMINAL_CUTOFFS (
  PORT_CALL_ID             VARCHAR2(30) NOT NULL,
  OUTBOUND_VOYAGE_ID       VARCHAR2(30) NOT NULL,
  LOAD_CUTOFF_AT           TIMESTAMP WITH TIME ZONE NOT NULL,
  CUTOFF_TYPE              VARCHAR2(30) NOT NULL,
  SOURCE_SYSTEM            VARCHAR2(40) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_CUTOFF_PK PRIMARY KEY (PORT_CALL_ID, OUTBOUND_VOYAGE_ID),
  CONSTRAINT MARITIME_SS_CUTOFF_CALL_FK
    FOREIGN KEY (PORT_CALL_ID) REFERENCES MARITIME_DEMO.MARITIME_SS_PORT_CALLS (PORT_CALL_ID),
  CONSTRAINT MARITIME_SS_CUTOFF_VOYAGE_FK
    FOREIGN KEY (OUTBOUND_VOYAGE_ID) REFERENCES MARITIME_DEMO.MARITIME_SS_VOYAGES (VOYAGE_ID),
  CONSTRAINT MARITIME_SS_CUTOFF_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_INCIDENTS (
  INCIDENT_ID              VARCHAR2(30),
  PORT_CALL_ID             VARCHAR2(30) NOT NULL,
  INCIDENT_TYPE            VARCHAR2(30) NOT NULL,
  OPENED_AT                TIMESTAMP WITH TIME ZONE NOT NULL,
  INCIDENT_STATUS          VARCHAR2(20) NOT NULL,
  SEVERITY                 VARCHAR2(20) NOT NULL,
  RECORDED_DELAY_MIN       NUMBER(6) NOT NULL,
  SUMMARY               VARCHAR2(1000) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_INCIDENT_PK PRIMARY KEY (INCIDENT_ID),
  CONSTRAINT MARITIME_SS_INCIDENT_CALL_FK
    FOREIGN KEY (PORT_CALL_ID) REFERENCES MARITIME_DEMO.MARITIME_SS_PORT_CALLS (PORT_CALL_ID),
  CONSTRAINT MARITIME_SS_INCIDENT_TYPE_CK CHECK (INCIDENT_TYPE = 'ETA_CHANGE'),
  CONSTRAINT MARITIME_SS_INCIDENT_STATUS_CK
    CHECK (INCIDENT_STATUS IN ('OPEN', 'CLOSED')),
  CONSTRAINT MARITIME_SS_INCIDENT_SEVERITY_CK
    CHECK (SEVERITY IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
  CONSTRAINT MARITIME_SS_INCIDENT_DELAY_CK CHECK (RECORDED_DELAY_MIN >= 0),
  CONSTRAINT MARITIME_SS_INCIDENT_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

ALTER TABLE MARITIME_DEMO.MARITIME_SS_FIXTURE_MANIFEST
  ADD CONSTRAINT MARITIME_SS_MANIFEST_INCIDENT_FK
  FOREIGN KEY (SCENARIO_ID)
  REFERENCES MARITIME_DEMO.MARITIME_SS_INCIDENTS (INCIDENT_ID)
  DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE MARITIME_DEMO.MARITIME_SS_BOOKINGS (
  BOOKING_ID               VARCHAR2(30),
  BOOKING_NO               VARCHAR2(30) NOT NULL,
  CUSTOMER_PRIORITY        VARCHAR2(20) NOT NULL,
  CARGO_CATEGORY           VARCHAR2(30) NOT NULL,
  TOTAL_TEU                NUMBER(6) NOT NULL,
  BOOKING_STATUS           VARCHAR2(20) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_BOOKING_PK PRIMARY KEY (BOOKING_ID),
  CONSTRAINT MARITIME_SS_BOOKING_NO_UQ UNIQUE (BOOKING_NO),
  CONSTRAINT MARITIME_SS_BOOKING_PRIORITY_CK
    CHECK (CUSTOMER_PRIORITY IN ('STANDARD', 'PRIORITY', 'MISSION_CRITICAL')),
  CONSTRAINT MARITIME_SS_BOOKING_TEU_CK CHECK (TOTAL_TEU > 0),
  CONSTRAINT MARITIME_SS_BOOKING_STATUS_CK
    CHECK (BOOKING_STATUS IN ('CONFIRMED', 'CONTROL')),
  CONSTRAINT MARITIME_SS_BOOKING_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_CONTAINERS (
  CONTAINER_ID             VARCHAR2(30),
  CONTAINER_NO             VARCHAR2(20) NOT NULL,
  ISO_TYPE                 VARCHAR2(10) NOT NULL,
  REEFER_YN                CHAR(1) NOT NULL,
  DANGEROUS_GOODS_YN       CHAR(1) NOT NULL,
  PRIORITY_CODE            VARCHAR2(20) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_CONTAINER_PK PRIMARY KEY (CONTAINER_ID),
  CONSTRAINT MARITIME_SS_CONTAINER_NO_UQ UNIQUE (CONTAINER_NO),
  CONSTRAINT MARITIME_SS_CONTAINER_REEFER_CK CHECK (REEFER_YN IN ('Y', 'N')),
  CONSTRAINT MARITIME_SS_CONTAINER_DG_CK CHECK (DANGEROUS_GOODS_YN IN ('Y', 'N')),
  CONSTRAINT MARITIME_SS_CONTAINER_PRIORITY_CK
    CHECK (PRIORITY_CODE IN ('STANDARD', 'PRIORITY', 'MISSION_CRITICAL')),
  CONSTRAINT MARITIME_SS_CONTAINER_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_BOOKING_CONTAINERS (
  EDGE_ID                  VARCHAR2(40),
  BOOKING_ID               VARCHAR2(30) NOT NULL,
  CONTAINER_ID             VARCHAR2(30) NOT NULL,
  ALLOCATION_TEU           NUMBER(4) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_BC_PK PRIMARY KEY (EDGE_ID),
  CONSTRAINT MARITIME_SS_BC_BOOKING_FK
    FOREIGN KEY (BOOKING_ID) REFERENCES MARITIME_DEMO.MARITIME_SS_BOOKINGS (BOOKING_ID),
  CONSTRAINT MARITIME_SS_BC_CONTAINER_FK
    FOREIGN KEY (CONTAINER_ID) REFERENCES MARITIME_DEMO.MARITIME_SS_CONTAINERS (CONTAINER_ID),
  CONSTRAINT MARITIME_SS_BC_CONTAINER_UQ UNIQUE (CONTAINER_ID),
  CONSTRAINT MARITIME_SS_BC_TEU_CK CHECK (ALLOCATION_TEU IN (1, 2)),
  CONSTRAINT MARITIME_SS_BC_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE TABLE MARITIME_DEMO.MARITIME_SS_CONNECTIONS (
  CONNECTION_ID            VARCHAR2(40),
  INBOUND_VOYAGE_ID        VARCHAR2(30) NOT NULL,
  OUTBOUND_VOYAGE_ID       VARCHAR2(30) NOT NULL,
  PORT_CALL_ID             VARCHAR2(30) NOT NULL,
  CONTAINER_ID             VARCHAR2(30) NOT NULL,
  PLANNED_READY_OFFSET_MIN NUMBER(6) NOT NULL,
  CONNECTION_STATE         VARCHAR2(20) NOT NULL,
  DATA_SCOPE               VARCHAR2(40) NOT NULL,
  CONSTRAINT MARITIME_SS_CONNECTION_PK PRIMARY KEY (CONNECTION_ID),
  CONSTRAINT MARITIME_SS_CONN_INBOUND_CALL_FK
    FOREIGN KEY (INBOUND_VOYAGE_ID, PORT_CALL_ID)
    REFERENCES MARITIME_DEMO.MARITIME_SS_PORT_CALLS (VOYAGE_ID, PORT_CALL_ID),
  CONSTRAINT MARITIME_SS_CONN_CUTOFF_FK
    FOREIGN KEY (PORT_CALL_ID, OUTBOUND_VOYAGE_ID)
    REFERENCES MARITIME_DEMO.MARITIME_SS_TERMINAL_CUTOFFS (PORT_CALL_ID, OUTBOUND_VOYAGE_ID),
  CONSTRAINT MARITIME_SS_CONN_CONTAINER_FK
    FOREIGN KEY (CONTAINER_ID) REFERENCES MARITIME_DEMO.MARITIME_SS_CONTAINERS (CONTAINER_ID),
  CONSTRAINT MARITIME_SS_CONN_BOOKING_EDGE_FK
    FOREIGN KEY (CONTAINER_ID)
    REFERENCES MARITIME_DEMO.MARITIME_SS_BOOKING_CONTAINERS (CONTAINER_ID),
  CONSTRAINT MARITIME_SS_CONN_ROUTE_UQ
    UNIQUE (PORT_CALL_ID, OUTBOUND_VOYAGE_ID, CONTAINER_ID),
  CONSTRAINT MARITIME_SS_CONN_OFFSET_CK CHECK (PLANNED_READY_OFFSET_MIN >= 0),
  CONSTRAINT MARITIME_SS_CONN_STATE_CK
    CHECK (CONNECTION_STATE IN ('PLANNED', 'CONTROL')),
  CONSTRAINT MARITIME_SS_CONN_SCOPE_CK
    CHECK (DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO')
);

CREATE INDEX MARITIME_DEMO.MARITIME_SS_ETA_CALL_IX
  ON MARITIME_DEMO.MARITIME_SS_ETA_EVENTS (PORT_CALL_ID, REVISION_NO DESC);

CREATE INDEX MARITIME_DEMO.MARITIME_SS_CONN_CALL_IX
  ON MARITIME_DEMO.MARITIME_SS_CONNECTIONS (PORT_CALL_ID, INBOUND_VOYAGE_ID);

CREATE INDEX MARITIME_DEMO.MARITIME_SS_CONN_CONTAINER_IX
  ON MARITIME_DEMO.MARITIME_SS_CONNECTIONS (CONTAINER_ID);

DECLARE
  l_table_count                NUMBER;
  l_named_constraint_count     NUMBER;
  l_bad_constraint             NUMBER;
  l_manifest_incident_fk_ok    NUMBER;
  l_connection_booking_fk_ok   NUMBER;
  l_policy_index_ok            NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_table_count
    FROM USER_TABLES
   WHERE TABLE_NAME IN (
     'MARITIME_SS_DEMO_CLOCK', 'MARITIME_SS_POLICY_VERSIONS', 'MARITIME_SS_FIXTURE_MANIFEST',
     'MARITIME_SS_VESSELS', 'MARITIME_SS_VOYAGES', 'MARITIME_SS_PORTS', 'MARITIME_SS_PORT_CALLS',
     'MARITIME_SS_ETA_EVENTS', 'MARITIME_SS_TERMINAL_CUTOFFS', 'MARITIME_SS_INCIDENTS',
     'MARITIME_SS_BOOKINGS', 'MARITIME_SS_CONTAINERS', 'MARITIME_SS_BOOKING_CONTAINERS',
     'MARITIME_SS_CONNECTIONS'
   );

  SELECT COUNT(*)
    INTO l_named_constraint_count
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME LIKE 'MARITIME\_SS\_%' ESCAPE '\';

  SELECT COUNT(*)
    INTO l_bad_constraint
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME LIKE 'MARITIME\_SS\_%' ESCAPE '\'
     AND (STATUS <> 'ENABLED' OR VALIDATED <> 'VALIDATED');

  SELECT COUNT(*)
    INTO l_manifest_incident_fk_ok
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'MARITIME_SS_MANIFEST_INCIDENT_FK'
     AND TABLE_NAME = 'MARITIME_SS_FIXTURE_MANIFEST'
     AND CONSTRAINT_TYPE = 'R'
     AND STATUS = 'ENABLED'
     AND VALIDATED = 'VALIDATED'
     AND DEFERRABLE = 'DEFERRABLE'
     AND DEFERRED = 'DEFERRED';

  SELECT COUNT(*)
    INTO l_connection_booking_fk_ok
    FROM USER_CONSTRAINTS
   WHERE CONSTRAINT_NAME = 'MARITIME_SS_CONN_BOOKING_EDGE_FK'
     AND TABLE_NAME = 'MARITIME_SS_CONNECTIONS'
     AND CONSTRAINT_TYPE = 'R'
     AND STATUS = 'ENABLED'
     AND VALIDATED = 'VALIDATED';

  SELECT COUNT(*)
    INTO l_policy_index_ok
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'MARITIME_SS_POLICY_ONE_ACTIVE_UI'
     AND STATUS = 'VALID'
     AND UNIQUENESS = 'UNIQUE';

  IF l_table_count <> 14
     OR l_named_constraint_count <> 77
     OR l_bad_constraint <> 0
     OR l_manifest_incident_fk_ok <> 1
     OR l_connection_booking_fk_ok <> 1
     OR l_policy_index_ok <> 1 THEN
    RAISE_APPLICATION_ERROR(
      -20002,
      'DDL postcondition failed: tables=' || l_table_count
      || ', named_constraints=' || l_named_constraint_count
      || ', bad_constraints=' || l_bad_constraint
      || ', manifest_incident_fk=' || l_manifest_incident_fk_ok
      || ', connection_booking_fk=' || l_connection_booking_fk_ok
      || ', active_policy_index=' || l_policy_index_ok
    );
  END IF;

  DBMS_OUTPUT.PUT_LINE('PASS MARITIME_SS relational DDL created and validated');
END;
/
