-- Maritime Actionable Ontology Demo Kit
-- Deterministic synthetic golden scenario. Key-based MERGE makes this file rerunnable.

SET SERVEROUTPUT ON

DECLARE
  l_user                  VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));
  l_manifest_postcondition NUMBER;
  l_future_postcondition   NUMBER;
  l_connection_postcondition NUMBER;
BEGIN
  IF l_user <> 'MARITIME_DEMO'
     OR UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')) <> 'MARITIME_DEMO' THEN
    RAISE_APPLICATION_ERROR(-20000, 'Connect directly as MARITIME_DEMO.');
  END IF;

MERGE INTO MARITIME_DEMO.MARITIME_SS_DEMO_CLOCK t
USING (
  SELECT
    1 AS CLOCK_ID,
    TO_TIMESTAMP_TZ(
      '2026-08-12 09:00:00 UTC',
      'YYYY-MM-DD HH24:MI:SS TZR'
    ) AS AS_OF_TS,
    'UTC' AS TIMEZONE_REGION,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
) s
ON (t.CLOCK_ID = s.CLOCK_ID)
WHEN MATCHED THEN UPDATE SET
  t.AS_OF_TS = s.AS_OF_TS,
  t.TIMEZONE_REGION = s.TIMEZONE_REGION,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  CLOCK_ID, AS_OF_TS, TIMEZONE_REGION, DATA_SCOPE
) VALUES (
  s.CLOCK_ID, s.AS_OF_TS, s.TIMEZONE_REGION, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_POLICY_VERSIONS t
USING (
  SELECT
    'MARITIME-AO-CONNECTION-0.1.0' AS POLICY_VERSION,
    'Y' AS ACTIVE_YN,
    TO_TIMESTAMP_TZ(
      '2026-08-12 00:00:00 UTC',
      'YYYY-MM-DD HH24:MI:SS TZR'
    ) AS EFFECTIVE_FROM_TS,
    90 AS TIGHT_THRESHOLD_MIN,
    5 AS MAX_INGEST_LAG_MIN,
    'PREVIEW_ONLY' AS APPROVAL_STATE,
    'N' AS EXTERNAL_EXECUTION_YN,
    'slack<0 MISS, 0<=slack<90 TIGHT, slack>=90 KEEP' AS POLICY_SUMMARY,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
) s
ON (t.POLICY_VERSION = s.POLICY_VERSION)
WHEN MATCHED THEN UPDATE SET
  t.ACTIVE_YN = s.ACTIVE_YN,
  t.EFFECTIVE_FROM_TS = s.EFFECTIVE_FROM_TS,
  t.TIGHT_THRESHOLD_MIN = s.TIGHT_THRESHOLD_MIN,
  t.MAX_INGEST_LAG_MIN = s.MAX_INGEST_LAG_MIN,
  t.APPROVAL_STATE = s.APPROVAL_STATE,
  t.EXTERNAL_EXECUTION_YN = s.EXTERNAL_EXECUTION_YN,
  t.POLICY_SUMMARY = s.POLICY_SUMMARY,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  POLICY_VERSION, ACTIVE_YN, EFFECTIVE_FROM_TS, TIGHT_THRESHOLD_MIN,
  MAX_INGEST_LAG_MIN, APPROVAL_STATE, EXTERNAL_EXECUTION_YN,
  POLICY_SUMMARY, DATA_SCOPE
) VALUES (
  s.POLICY_VERSION, s.ACTIVE_YN, s.EFFECTIVE_FROM_TS, s.TIGHT_THRESHOLD_MIN,
  s.MAX_INGEST_LAG_MIN, s.APPROVAL_STATE, s.EXTERNAL_EXECUTION_YN,
  s.POLICY_SUMMARY, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_FIXTURE_MANIFEST t
USING (
  SELECT
    'MARITIME-AO-FIXTURE-0.1.0' AS FIXTURE_VERSION,
    'MARITIME-AO-CONTRACT-0.1.0' AS CONTRACT_VERSION,
    'MARITIME-AO-ONTOLOGY-0.2.0' AS ONTOLOGY_VERSION,
    'MARITIME-AO-CONNECTION-0.1.0' AS POLICY_VERSION,
    'INC-MAR-0001' AS SCENARIO_ID,
    TO_TIMESTAMP_TZ(
      '2026-08-12 09:00:00 UTC',
      'YYYY-MM-DD HH24:MI:SS TZR'
    ) AS DATA_AS_OF_TS,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
) s
ON (t.FIXTURE_VERSION = s.FIXTURE_VERSION)
WHEN MATCHED THEN UPDATE SET
  t.CONTRACT_VERSION = s.CONTRACT_VERSION,
  t.ONTOLOGY_VERSION = s.ONTOLOGY_VERSION,
  t.POLICY_VERSION = s.POLICY_VERSION,
  t.SCENARIO_ID = s.SCENARIO_ID,
  t.DATA_AS_OF_TS = s.DATA_AS_OF_TS,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  FIXTURE_VERSION, CONTRACT_VERSION, ONTOLOGY_VERSION, POLICY_VERSION,
  SCENARIO_ID, DATA_AS_OF_TS, DATA_SCOPE
) VALUES (
  s.FIXTURE_VERSION, s.CONTRACT_VERSION, s.ONTOLOGY_VERSION, s.POLICY_VERSION,
  s.SCENARIO_ID, s.DATA_AS_OF_TS, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_VESSELS t
USING (
  SELECT 'VES-MAR-DEMO-01' VESSEL_ID, 'MARITIME DEMO INBOUND' VESSEL_NAME,
         CAST(NULL AS VARCHAR2(20)) IMO_NUMBER, 'ACTIVE' VESSEL_STATUS,
         'SYNTHETIC_SHIP_SHORE_DEMO' DATA_SCOPE FROM DUAL
  UNION ALL
  SELECT 'VES-MAR-DEMO-02', 'MARITIME DEMO CONNECT A', NULL, 'ACTIVE',
         'SYNTHETIC_SHIP_SHORE_DEMO' FROM DUAL
  UNION ALL
  SELECT 'VES-MAR-DEMO-03', 'MARITIME DEMO CONNECT B', NULL, 'ACTIVE',
         'SYNTHETIC_SHIP_SHORE_DEMO' FROM DUAL
  UNION ALL
  SELECT 'VES-MAR-DEMO-04', 'MARITIME DEMO CONNECT C', NULL, 'ACTIVE',
         'SYNTHETIC_SHIP_SHORE_DEMO' FROM DUAL
  UNION ALL
  SELECT 'VES-MAR-DEMO-05', 'MARITIME DEMO CONTROL', NULL, 'CONTROL',
         'SYNTHETIC_SHIP_SHORE_DEMO' FROM DUAL
) s
ON (t.VESSEL_ID = s.VESSEL_ID)
WHEN MATCHED THEN UPDATE SET
  t.VESSEL_NAME = s.VESSEL_NAME,
  t.IMO_NUMBER = s.IMO_NUMBER,
  t.VESSEL_STATUS = s.VESSEL_STATUS,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  VESSEL_ID, VESSEL_NAME, IMO_NUMBER, VESSEL_STATUS, DATA_SCOPE
) VALUES (
  s.VESSEL_ID, s.VESSEL_NAME, s.IMO_NUMBER, s.VESSEL_STATUS, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_VOYAGES t
USING (
  SELECT 'VYG-DEMO-2608E' VOYAGE_ID, 'DEMO-2608E' VOYAGE_NO,
         'VES-MAR-DEMO-01' VESSEL_ID, 'INBOUND' VOYAGE_ROLE,
         'MAR-DEMO-01' SERVICE_CODE, 'IN_PROGRESS' VOYAGE_STATUS,
         'SYNTHETIC_SHIP_SHORE_DEMO' DATA_SCOPE FROM DUAL
  UNION ALL
  SELECT 'VYG-DEMO-2609A', 'DEMO-2609A', 'VES-MAR-DEMO-02', 'OUTBOUND',
         'MAR-DEMO-A', 'PLANNED', 'SYNTHETIC_SHIP_SHORE_DEMO' FROM DUAL
  UNION ALL
  SELECT 'VYG-DEMO-2609B', 'DEMO-2609B', 'VES-MAR-DEMO-03', 'OUTBOUND',
         'MAR-DEMO-B', 'PLANNED', 'SYNTHETIC_SHIP_SHORE_DEMO' FROM DUAL
  UNION ALL
  SELECT 'VYG-DEMO-2609C', 'DEMO-2609C', 'VES-MAR-DEMO-04', 'OUTBOUND',
         'MAR-DEMO-C', 'PLANNED', 'SYNTHETIC_SHIP_SHORE_DEMO' FROM DUAL
  UNION ALL
  SELECT 'VYG-CTRL-2608W', 'CTRL-2608W', 'VES-MAR-DEMO-05', 'CONTROL',
         'SS-CONTROL', 'CONTROL', 'SYNTHETIC_SHIP_SHORE_DEMO' FROM DUAL
  UNION ALL
  SELECT 'VYG-CTRL-2609W', 'CTRL-2609W', 'VES-MAR-DEMO-05', 'CONTROL',
         'SS-CONTROL', 'CONTROL', 'SYNTHETIC_SHIP_SHORE_DEMO' FROM DUAL
) s
ON (t.VOYAGE_ID = s.VOYAGE_ID)
WHEN MATCHED THEN UPDATE SET
  t.VOYAGE_NO = s.VOYAGE_NO,
  t.VESSEL_ID = s.VESSEL_ID,
  t.VOYAGE_ROLE = s.VOYAGE_ROLE,
  t.SERVICE_CODE = s.SERVICE_CODE,
  t.VOYAGE_STATUS = s.VOYAGE_STATUS,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  VOYAGE_ID, VOYAGE_NO, VESSEL_ID, VOYAGE_ROLE, SERVICE_CODE,
  VOYAGE_STATUS, DATA_SCOPE
) VALUES (
  s.VOYAGE_ID, s.VOYAGE_NO, s.VESSEL_ID, s.VOYAGE_ROLE, s.SERVICE_CODE,
  s.VOYAGE_STATUS, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_PORTS t
USING (
  SELECT
    'HBA' AS PORT_CODE,
    'Harbor Alpha' AS PORT_NAME,
    'KR' AS COUNTRY_CODE,
    'UTC' AS TIMEZONE_REGION,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
) s
ON (t.PORT_CODE = s.PORT_CODE)
WHEN MATCHED THEN UPDATE SET
  t.PORT_NAME = s.PORT_NAME,
  t.COUNTRY_CODE = s.COUNTRY_CODE,
  t.TIMEZONE_REGION = s.TIMEZONE_REGION,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  PORT_CODE, PORT_NAME, COUNTRY_CODE, TIMEZONE_REGION, DATA_SCOPE
) VALUES (
  s.PORT_CODE, s.PORT_NAME, s.COUNTRY_CODE, s.TIMEZONE_REGION, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_PORT_CALLS t
USING (
  SELECT
    'PC-ALPHA-260812' AS PORT_CALL_ID,
    'VYG-DEMO-2608E' AS VOYAGE_ID,
    'HBA' AS PORT_CODE,
    'HARBOR-ALPHA-T1' AS TERMINAL_CODE,
    TO_TIMESTAMP_TZ(
      '2026-08-12 07:00:00 UTC',
      'YYYY-MM-DD HH24:MI:SS TZR'
    ) AS PLANNED_ARRIVAL_AT,
    'DELAY_REVIEW' AS PORT_CALL_STATUS,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
  UNION ALL
  SELECT
    'PC-CTRL-260812',
    'VYG-CTRL-2608W',
    'HBA',
    'HARBOR-ALPHA-T1',
    TO_TIMESTAMP_TZ(
      '2026-08-12 08:00:00 UTC',
      'YYYY-MM-DD HH24:MI:SS TZR'
    ),
    'CONTROL',
    'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
) s
ON (t.PORT_CALL_ID = s.PORT_CALL_ID)
WHEN MATCHED THEN UPDATE SET
  t.VOYAGE_ID = s.VOYAGE_ID,
  t.PORT_CODE = s.PORT_CODE,
  t.TERMINAL_CODE = s.TERMINAL_CODE,
  t.PLANNED_ARRIVAL_AT = s.PLANNED_ARRIVAL_AT,
  t.PORT_CALL_STATUS = s.PORT_CALL_STATUS,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  PORT_CALL_ID, VOYAGE_ID, PORT_CODE, TERMINAL_CODE,
  PLANNED_ARRIVAL_AT, PORT_CALL_STATUS, DATA_SCOPE
) VALUES (
  s.PORT_CALL_ID, s.VOYAGE_ID, s.PORT_CODE, s.TERMINAL_CODE,
  s.PLANNED_ARRIVAL_AT, s.PORT_CALL_STATUS, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_ETA_EVENTS t
USING (
  SELECT
    'ETA-MAR-0001' ETA_EVENT_ID,
    'PC-ALPHA-260812' PORT_CALL_ID,
    1 REVISION_NO,
    'VESSEL_GATEWAY' SOURCE_SYSTEM,
    TO_TIMESTAMP_TZ('2026-08-11 18:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR') SOURCE_EVENT_AT,
    TO_TIMESTAMP_TZ('2026-08-11 18:03:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR') RECEIVED_AT,
    TO_TIMESTAMP_TZ('2026-08-12 07:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR') REPORTED_ETA_AT,
    'ACCEPTED' PAYLOAD_STATUS,
    'SYNTHETIC_SHIP_SHORE_DEMO' DATA_SCOPE
  FROM DUAL
  UNION ALL
  SELECT
    'ETA-MAR-0002', 'PC-ALPHA-260812', 2, 'VESSEL_GATEWAY',
    TO_TIMESTAMP_TZ('2026-08-12 08:55:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    TO_TIMESTAMP_TZ('2026-08-12 08:57:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    TO_TIMESTAMP_TZ('2026-08-12 14:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    'ACCEPTED', 'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
  UNION ALL
  SELECT
    'ETA-MAR-0000-LATE', 'PC-ALPHA-260812', 0, 'VESSEL_GATEWAY',
    TO_TIMESTAMP_TZ('2026-08-11 17:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    TO_TIMESTAMP_TZ('2026-08-12 08:58:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    TO_TIMESTAMP_TZ('2026-08-12 06:30:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    'ACCEPTED', 'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
  UNION ALL
  SELECT
    'ETA-MAR-CTRL-0001', 'PC-CTRL-260812', 1, 'VESSEL_GATEWAY',
    TO_TIMESTAMP_TZ('2026-08-12 07:50:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    TO_TIMESTAMP_TZ('2026-08-12 07:52:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    TO_TIMESTAMP_TZ('2026-08-12 08:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    'CONTROL', 'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
  UNION ALL
  SELECT
    'ETA-MAR-0003-FUTURE', 'PC-ALPHA-260812', 3, 'VESSEL_GATEWAY',
    TO_TIMESTAMP_TZ('2026-08-12 09:05:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    TO_TIMESTAMP_TZ('2026-08-12 09:07:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    TO_TIMESTAMP_TZ('2026-08-12 15:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    'ACCEPTED', 'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
) s
ON (t.ETA_EVENT_ID = s.ETA_EVENT_ID)
WHEN MATCHED THEN UPDATE SET
  t.PORT_CALL_ID = s.PORT_CALL_ID,
  t.REVISION_NO = s.REVISION_NO,
  t.SOURCE_SYSTEM = s.SOURCE_SYSTEM,
  t.SOURCE_EVENT_AT = s.SOURCE_EVENT_AT,
  t.RECEIVED_AT = s.RECEIVED_AT,
  t.REPORTED_ETA_AT = s.REPORTED_ETA_AT,
  t.PAYLOAD_STATUS = s.PAYLOAD_STATUS,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  ETA_EVENT_ID, PORT_CALL_ID, REVISION_NO, SOURCE_SYSTEM,
  SOURCE_EVENT_AT, RECEIVED_AT, REPORTED_ETA_AT, PAYLOAD_STATUS, DATA_SCOPE
) VALUES (
  s.ETA_EVENT_ID, s.PORT_CALL_ID, s.REVISION_NO, s.SOURCE_SYSTEM,
  s.SOURCE_EVENT_AT, s.RECEIVED_AT, s.REPORTED_ETA_AT, s.PAYLOAD_STATUS, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_TERMINAL_CUTOFFS t
USING (
  SELECT
    'PC-ALPHA-260812' PORT_CALL_ID,
    'VYG-DEMO-2609A' OUTBOUND_VOYAGE_ID,
    TO_TIMESTAMP_TZ('2026-08-12 14:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR') LOAD_CUTOFF_AT,
    'TRANSLOAD_CUTOFF' CUTOFF_TYPE,
    'TERMINAL_PLAN' SOURCE_SYSTEM,
    'SYNTHETIC_SHIP_SHORE_DEMO' DATA_SCOPE
  FROM DUAL
  UNION ALL
  SELECT
    'PC-ALPHA-260812', 'VYG-DEMO-2609B',
    TO_TIMESTAMP_TZ('2026-08-12 18:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    'TRANSLOAD_CUTOFF', 'TERMINAL_PLAN', 'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
  UNION ALL
  SELECT
    'PC-ALPHA-260812', 'VYG-DEMO-2609C',
    TO_TIMESTAMP_TZ('2026-08-12 20:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    'TRANSLOAD_CUTOFF', 'TERMINAL_PLAN', 'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
  UNION ALL
  SELECT
    'PC-CTRL-260812', 'VYG-CTRL-2609W',
    TO_TIMESTAMP_TZ('2026-08-12 10:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'),
    'TRANSLOAD_CUTOFF', 'TERMINAL_PLAN', 'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
) s
ON (
  t.PORT_CALL_ID = s.PORT_CALL_ID
  AND t.OUTBOUND_VOYAGE_ID = s.OUTBOUND_VOYAGE_ID
)
WHEN MATCHED THEN UPDATE SET
  t.LOAD_CUTOFF_AT = s.LOAD_CUTOFF_AT,
  t.CUTOFF_TYPE = s.CUTOFF_TYPE,
  t.SOURCE_SYSTEM = s.SOURCE_SYSTEM,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  PORT_CALL_ID, OUTBOUND_VOYAGE_ID, LOAD_CUTOFF_AT,
  CUTOFF_TYPE, SOURCE_SYSTEM, DATA_SCOPE
) VALUES (
  s.PORT_CALL_ID, s.OUTBOUND_VOYAGE_ID, s.LOAD_CUTOFF_AT,
  s.CUTOFF_TYPE, s.SOURCE_SYSTEM, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_INCIDENTS t
USING (
  SELECT
    'INC-MAR-0001' AS INCIDENT_ID,
    'PC-ALPHA-260812' AS PORT_CALL_ID,
    'ETA_CHANGE' AS INCIDENT_TYPE,
    TO_TIMESTAMP_TZ(
      '2026-08-12 08:57:00 UTC',
      'YYYY-MM-DD HH24:MI:SS TZR'
    ) AS OPENED_AT,
    'OPEN' AS INCIDENT_STATUS,
    'HIGH' AS SEVERITY,
    420 AS RECORDED_DELAY_MIN,
    'Harbor Alpha Port Call의 최신 ETA가 기존 계획보다 420분 늦어진 합성 검토 사건' AS SUMMARY,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
) s
ON (t.INCIDENT_ID = s.INCIDENT_ID)
WHEN MATCHED THEN UPDATE SET
  t.PORT_CALL_ID = s.PORT_CALL_ID,
  t.INCIDENT_TYPE = s.INCIDENT_TYPE,
  t.OPENED_AT = s.OPENED_AT,
  t.INCIDENT_STATUS = s.INCIDENT_STATUS,
  t.SEVERITY = s.SEVERITY,
  t.RECORDED_DELAY_MIN = s.RECORDED_DELAY_MIN,
  t.SUMMARY = s.SUMMARY,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  INCIDENT_ID, PORT_CALL_ID, INCIDENT_TYPE, OPENED_AT,
  INCIDENT_STATUS, SEVERITY, RECORDED_DELAY_MIN, SUMMARY, DATA_SCOPE
) VALUES (
  s.INCIDENT_ID, s.PORT_CALL_ID, s.INCIDENT_TYPE, s.OPENED_AT,
  s.INCIDENT_STATUS, s.SEVERITY, s.RECORDED_DELAY_MIN, s.SUMMARY, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_BOOKINGS t
USING (
  SELECT
    'BKG-MAR-' || LPAD(TO_CHAR(LEVEL), 3, '0') AS BOOKING_ID,
    'DEMO-BKG-' || LPAD(TO_CHAR(LEVEL), 3, '0') AS BOOKING_NO,
    CASE
      WHEN LEVEL <= 3 THEN 'MISSION_CRITICAL'
      WHEN LEVEL <= 8 THEN 'PRIORITY'
      ELSE 'STANDARD'
    END AS CUSTOMER_PRIORITY,
    CASE MOD(LEVEL, 4)
      WHEN 0 THEN 'REEFER_FOOD'
      WHEN 1 THEN 'ELECTRONICS'
      WHEN 2 THEN 'AUTO_PARTS'
      ELSE 'GENERAL_CARGO'
    END AS CARGO_CATEGORY,
    4 AS TOTAL_TEU,
    'CONFIRMED' AS BOOKING_STATUS,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
  CONNECT BY LEVEL <= 18
  UNION ALL
  SELECT
    'BKG-MAR-CTRL', 'DEMO-BKG-CTRL', 'STANDARD', 'GENERAL_CARGO',
    2, 'CONTROL', 'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
) s
ON (t.BOOKING_ID = s.BOOKING_ID)
WHEN MATCHED THEN UPDATE SET
  t.BOOKING_NO = s.BOOKING_NO,
  t.CUSTOMER_PRIORITY = s.CUSTOMER_PRIORITY,
  t.CARGO_CATEGORY = s.CARGO_CATEGORY,
  t.TOTAL_TEU = s.TOTAL_TEU,
  t.BOOKING_STATUS = s.BOOKING_STATUS,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  BOOKING_ID, BOOKING_NO, CUSTOMER_PRIORITY, CARGO_CATEGORY,
  TOTAL_TEU, BOOKING_STATUS, DATA_SCOPE
) VALUES (
  s.BOOKING_ID, s.BOOKING_NO, s.CUSTOMER_PRIORITY, s.CARGO_CATEGORY,
  s.TOTAL_TEU, s.BOOKING_STATUS, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_CONTAINERS t
USING (
  SELECT
    'CNT-MAR-' || LPAD(TO_CHAR(LEVEL), 3, '0') AS CONTAINER_ID,
    'SYNSS' || LPAD(TO_CHAR(LEVEL), 6, '0') AS CONTAINER_NO,
    CASE WHEN MOD(LEVEL, 12) = 0 THEN '45R1' ELSE '42G1' END AS ISO_TYPE,
    CASE WHEN MOD(LEVEL, 12) = 0 THEN 'Y' ELSE 'N' END AS REEFER_YN,
    CASE WHEN MOD(LEVEL, 10) = 0 THEN 'Y' ELSE 'N' END AS DANGEROUS_GOODS_YN,
    CASE
      WHEN LEVEL <= 6 THEN 'MISSION_CRITICAL'
      WHEN LEVEL <= 15 THEN 'PRIORITY'
      ELSE 'STANDARD'
    END AS PRIORITY_CODE,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
  CONNECT BY LEVEL <= 36
  UNION ALL
  SELECT
    'CNT-MAR-CTRL', 'SYNSSCTRL01', '42G1', 'N', 'N', 'STANDARD',
    'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
) s
ON (t.CONTAINER_ID = s.CONTAINER_ID)
WHEN MATCHED THEN UPDATE SET
  t.CONTAINER_NO = s.CONTAINER_NO,
  t.ISO_TYPE = s.ISO_TYPE,
  t.REEFER_YN = s.REEFER_YN,
  t.DANGEROUS_GOODS_YN = s.DANGEROUS_GOODS_YN,
  t.PRIORITY_CODE = s.PRIORITY_CODE,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  CONTAINER_ID, CONTAINER_NO, ISO_TYPE, REEFER_YN,
  DANGEROUS_GOODS_YN, PRIORITY_CODE, DATA_SCOPE
) VALUES (
  s.CONTAINER_ID, s.CONTAINER_NO, s.ISO_TYPE, s.REEFER_YN,
  s.DANGEROUS_GOODS_YN, s.PRIORITY_CODE, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_BOOKING_CONTAINERS t
USING (
  SELECT
    'E-BC-' || LPAD(TO_CHAR(LEVEL), 3, '0') AS EDGE_ID,
    'BKG-MAR-' || LPAD(TO_CHAR(CEIL(LEVEL / 2)), 3, '0') AS BOOKING_ID,
    'CNT-MAR-' || LPAD(TO_CHAR(LEVEL), 3, '0') AS CONTAINER_ID,
    2 AS ALLOCATION_TEU,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
  CONNECT BY LEVEL <= 36
  UNION ALL
  SELECT
    'E-BC-CTRL', 'BKG-MAR-CTRL', 'CNT-MAR-CTRL', 2,
    'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
) s
ON (t.EDGE_ID = s.EDGE_ID)
WHEN MATCHED THEN UPDATE SET
  t.BOOKING_ID = s.BOOKING_ID,
  t.CONTAINER_ID = s.CONTAINER_ID,
  t.ALLOCATION_TEU = s.ALLOCATION_TEU,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  EDGE_ID, BOOKING_ID, CONTAINER_ID, ALLOCATION_TEU, DATA_SCOPE
) VALUES (
  s.EDGE_ID, s.BOOKING_ID, s.CONTAINER_ID, s.ALLOCATION_TEU, s.DATA_SCOPE
);

MERGE INTO MARITIME_DEMO.MARITIME_SS_CONNECTIONS t
USING (
  SELECT
    'CONN-MAR-' || LPAD(TO_CHAR(LEVEL), 3, '0') AS CONNECTION_ID,
    'VYG-DEMO-2608E' AS INBOUND_VOYAGE_ID,
    CASE
      WHEN LEVEL <= 9 THEN 'VYG-DEMO-2609A'
      WHEN LEVEL <= 15 THEN 'VYG-DEMO-2609B'
      ELSE 'VYG-DEMO-2609C'
    END AS OUTBOUND_VOYAGE_ID,
    'PC-ALPHA-260812' AS PORT_CALL_ID,
    'CNT-MAR-' || LPAD(TO_CHAR(LEVEL), 3, '0') AS CONTAINER_ID,
    CASE
      WHEN LEVEL <= 9 THEN 130 + (10 * LEVEL)
      WHEN LEVEL <= 15 THEN 60 + (10 * LEVEL)
      ELSE 10 + (5 * LEVEL)
    END AS PLANNED_READY_OFFSET_MIN,
    'PLANNED' AS CONNECTION_STATE,
    'SYNTHETIC_SHIP_SHORE_DEMO' AS DATA_SCOPE
  FROM DUAL
  CONNECT BY LEVEL <= 36
  UNION ALL
  SELECT
    'CONN-MAR-CTRL', 'VYG-CTRL-2608W', 'VYG-CTRL-2609W',
    'PC-CTRL-260812', 'CNT-MAR-CTRL', 30, 'CONTROL',
    'SYNTHETIC_SHIP_SHORE_DEMO'
  FROM DUAL
) s
ON (t.CONNECTION_ID = s.CONNECTION_ID)
WHEN MATCHED THEN UPDATE SET
  t.INBOUND_VOYAGE_ID = s.INBOUND_VOYAGE_ID,
  t.OUTBOUND_VOYAGE_ID = s.OUTBOUND_VOYAGE_ID,
  t.PORT_CALL_ID = s.PORT_CALL_ID,
  t.CONTAINER_ID = s.CONTAINER_ID,
  t.PLANNED_READY_OFFSET_MIN = s.PLANNED_READY_OFFSET_MIN,
  t.CONNECTION_STATE = s.CONNECTION_STATE,
  t.DATA_SCOPE = s.DATA_SCOPE
WHEN NOT MATCHED THEN INSERT (
  CONNECTION_ID, INBOUND_VOYAGE_ID, OUTBOUND_VOYAGE_ID,
  PORT_CALL_ID, CONTAINER_ID, PLANNED_READY_OFFSET_MIN,
  CONNECTION_STATE, DATA_SCOPE
) VALUES (
  s.CONNECTION_ID, s.INBOUND_VOYAGE_ID, s.OUTBOUND_VOYAGE_ID,
  s.PORT_CALL_ID, s.CONTAINER_ID, s.PLANNED_READY_OFFSET_MIN,
  s.CONNECTION_STATE, s.DATA_SCOPE
);

SELECT COUNT(*)
  INTO l_manifest_postcondition
  FROM MARITIME_DEMO.MARITIME_SS_FIXTURE_MANIFEST
 WHERE FIXTURE_VERSION = 'MARITIME-AO-FIXTURE-0.1.0'
   AND SCENARIO_ID = 'INC-MAR-0001'
   AND POLICY_VERSION = 'MARITIME-AO-CONNECTION-0.1.0';

SELECT COUNT(*)
  INTO l_future_postcondition
  FROM MARITIME_DEMO.MARITIME_SS_ETA_EVENTS
 WHERE ETA_EVENT_ID = 'ETA-MAR-0003-FUTURE'
   AND REVISION_NO = 3
   AND RECEIVED_AT = TO_TIMESTAMP_TZ(
     '2026-08-12 09:07:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR'
   );

SELECT COUNT(*)
  INTO l_connection_postcondition
  FROM MARITIME_DEMO.MARITIME_SS_CONNECTIONS
 WHERE PORT_CALL_ID = 'PC-ALPHA-260812'
   AND CONNECTION_STATE = 'PLANNED';

IF l_manifest_postcondition <> 1
   OR l_future_postcondition <> 1
   OR l_connection_postcondition <> 36 THEN
  RAISE_APPLICATION_ERROR(
    -20120,
    'Fixture postcondition failed: manifest=' || l_manifest_postcondition
    || ', future_event=' || l_future_postcondition
    || ', main_connections=' || l_connection_postcondition
  );
END IF;

COMMIT;
DBMS_OUTPUT.PUT_LINE('PASS Maritime Actionable Ontology golden fixture merged atomically');
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;
END;
/

SELECT
  'FIXTURE_POSTCOMMIT_SNAPSHOT' AS STATUS,
  i.INCIDENT_ID,
  pc.VOYAGE_ID AS INBOUND_VOYAGE_ID,
  i.PORT_CALL_ID,
  m.POLICY_VERSION,
  m.FIXTURE_VERSION,
  m.DATA_AS_OF_TS,
  future.REVISION_NO AS POST_AS_OF_REVISION_NO,
  future.RECEIVED_AT AS POST_AS_OF_RECEIVED_AT,
  m.DATA_SCOPE,
  'revision 3 received after as-of and retained for exclusion proof' AS REPLAY_NOTE
FROM MARITIME_DEMO.MARITIME_SS_FIXTURE_MANIFEST m
JOIN MARITIME_DEMO.MARITIME_SS_INCIDENTS i
  ON i.INCIDENT_ID = m.SCENARIO_ID
JOIN MARITIME_DEMO.MARITIME_SS_PORT_CALLS pc
  ON pc.PORT_CALL_ID = i.PORT_CALL_ID
JOIN MARITIME_DEMO.MARITIME_SS_ETA_EVENTS future
  ON future.ETA_EVENT_ID = 'ETA-MAR-0003-FUTURE'
 AND future.PORT_CALL_ID = i.PORT_CALL_ID
 AND future.RECEIVED_AT > m.DATA_AS_OF_TS
WHERE m.FIXTURE_VERSION = 'MARITIME-AO-FIXTURE-0.1.0'
  AND m.POLICY_VERSION = 'MARITIME-AO-CONNECTION-0.1.0'
  AND m.DATA_SCOPE = 'SYNTHETIC_SHIP_SHORE_DEMO';
