-- Maritime Actionable Ontology Demo Kit
-- Read-only action candidates. No approval, mutation, message, or external execution.

SET SERVEROUTPUT ON

BEGIN
  IF UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER')) <> 'MARITIME_DEMO'
     OR UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')) <> 'MARITIME_DEMO' THEN
    RAISE_APPLICATION_ERROR(-20000, 'Connect directly as MARITIME_DEMO.');
  END IF;
END;
/

CREATE OR REPLACE VIEW MARITIME_DEMO.MARITIME_SS_ACTION_PREVIEW_V AS
SELECT
  'ACT-MAR-' || INCIDENT_ID || '-' || CONNECTION_ID || '-' || POLICY_VERSION
    AS ACTION_PREVIEW_ID,
  INCIDENT_ID,
  CONNECTION_ID,
  CONTAINER_ID,
  CONTAINER_NO,
  BOOKING_ID,
  BOOKING_NO,
  OUTBOUND_VOYAGE_ID,
  SELECTED_ETA_EVENT_ID,
  SELECTED_REVISION_NO,
  SELECTED_ETA_AT,
  SELECTED_SOURCE_EVENT_AT,
  SELECTED_RECEIVED_AT,
  DECISION_CODE,
  CONNECTION_SLACK_MINUTES,
  CASE
    WHEN DECISION_CODE = 'MISS' THEN 'REVIEW_ALTERNATE_VOYAGE'
    WHEN DECISION_CODE = 'TIGHT' THEN 'EXPEDITE_YARD_TRANSFER'
  END AS ACTION_TYPE,
  CASE
    WHEN DECISION_CODE = 'MISS'
      THEN 'Human review: assess alternate onward-voyage options'
    WHEN DECISION_CODE = 'TIGHT'
      THEN 'Human review: assess expedited terminal-transfer options'
  END AS ACTION_SUMMARY,
  CASE
    WHEN DECISION_CODE = 'MISS' THEN 'SHORE_OPERATIONS_MANAGER'
    WHEN DECISION_CODE = 'TIGHT' THEN 'TERMINAL_COORDINATOR'
  END AS REQUIRED_REVIEW_ROLE,
  LOAD_CUTOFF_AT AS REVIEW_BY_AT,
  FIXTURE_VERSION,
  CONTRACT_VERSION,
  ONTOLOGY_VERSION,
  POLICY_VERSION,
  CONTEXT_SCENARIO_ID,
  DATA_AS_OF_TS,
  RUN_MODE,
  RESULT_PROVENANCE,
  APPROVAL_STATE,
  EXTERNAL_EXECUTION_YN,
  'Y' AS WORKFLOW_ASSUMPTION_YN,
  'No approval request, booking change, terminal instruction, vessel command, or customer notification'
    AS SAFETY_NOTICE,
  DATA_SCOPE
FROM MARITIME_DEMO.MARITIME_SS_SEMANTIC_INPUT_V
WHERE DECISION_CODE IN ('MISS', 'TIGHT');

CREATE OR REPLACE VIEW MARITIME_DEMO.MARITIME_SS_ACTION_SUMMARY_V AS
SELECT
  INCIDENT_ID,
  COUNT(*) AS ACTION_PREVIEW_COUNT,
  SUM(CASE WHEN ACTION_TYPE = 'REVIEW_ALTERNATE_VOYAGE' THEN 1 ELSE 0 END)
    AS ALTERNATE_VOYAGE_REVIEW_COUNT,
  SUM(CASE WHEN ACTION_TYPE = 'EXPEDITE_YARD_TRANSFER' THEN 1 ELSE 0 END)
    AS YARD_EXPEDITE_REVIEW_COUNT,
  COUNT(DISTINCT REQUIRED_REVIEW_ROLE) AS REVIEW_ROLE_COUNT,
  MAX(SELECTED_ETA_EVENT_ID) AS SELECTED_ETA_EVENT_ID,
  MAX(SELECTED_REVISION_NO) AS SELECTED_REVISION_NO,
  MAX(SELECTED_ETA_AT) AS SELECTED_ETA_AT,
  MAX(SELECTED_SOURCE_EVENT_AT) AS SELECTED_SOURCE_EVENT_AT,
  MAX(SELECTED_RECEIVED_AT) AS SELECTED_RECEIVED_AT,
  MAX(FIXTURE_VERSION) AS FIXTURE_VERSION,
  MAX(CONTRACT_VERSION) AS CONTRACT_VERSION,
  MAX(ONTOLOGY_VERSION) AS ONTOLOGY_VERSION,
  MAX(POLICY_VERSION) AS POLICY_VERSION,
  MAX(CONTEXT_SCENARIO_ID) AS CONTEXT_SCENARIO_ID,
  MAX(DATA_AS_OF_TS) AS DATA_AS_OF_TS,
  MAX(RUN_MODE) AS RUN_MODE,
  MAX(RESULT_PROVENANCE) AS RESULT_PROVENANCE,
  MAX(APPROVAL_STATE) AS APPROVAL_STATE,
  MAX(EXTERNAL_EXECUTION_YN) AS EXTERNAL_EXECUTION_YN,
  MAX(WORKFLOW_ASSUMPTION_YN) AS WORKFLOW_ASSUMPTION_YN,
  MAX(DATA_SCOPE) AS DATA_SCOPE
FROM MARITIME_DEMO.MARITIME_SS_ACTION_PREVIEW_V
GROUP BY INCIDENT_ID;

COMMENT ON TABLE MARITIME_DEMO.MARITIME_SS_ACTION_PREVIEW_V IS
  'Read-only candidates derived from MISS/TIGHT decisions. It performs no operational write.';
COMMENT ON COLUMN MARITIME_DEMO.MARITIME_SS_ACTION_PREVIEW_V.APPROVAL_STATE IS
  'Always PREVIEW_ONLY in v0.';
COMMENT ON COLUMN MARITIME_DEMO.MARITIME_SS_ACTION_PREVIEW_V.EXTERNAL_EXECUTION_YN IS
  'Always N in v0; no external side effect is authorized.';

COMMENT ON COLUMN MARITIME_DEMO.MARITIME_SS_ACTION_PREVIEW_V.WORKFLOW_ASSUMPTION_YN IS
  'Y means this is a synthetic workflow assumption, not an observed operational execution.';

DECLARE
  l_valid_action_view_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_valid_action_view_count
    FROM USER_OBJECTS
   WHERE OBJECT_NAME IN ('MARITIME_SS_ACTION_PREVIEW_V', 'MARITIME_SS_ACTION_SUMMARY_V')
     AND OBJECT_TYPE = 'VIEW'
     AND STATUS = 'VALID';

  IF l_valid_action_view_count <> 2 THEN
    RAISE_APPLICATION_ERROR(
      -20410,
      'Action view postcondition failed: valid_views=' || l_valid_action_view_count
    );
  END IF;

  DBMS_OUTPUT.PUT_LINE('PASS MARITIME_SS action preview contracts created and validated');
END;
/
