-- Maritime Actionable Ontology Demo Kit
-- Oracle SQL Property Graph over relational tables and validated edge snapshots.

SET SERVEROUTPUT ON

BEGIN
  IF UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER')) <> 'MARITIME_DEMO'
     OR UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')) <> 'MARITIME_DEMO' THEN
    RAISE_APPLICATION_ERROR(-20000, 'Connect directly as MARITIME_DEMO.');
  END IF;
END;
/

DECLARE
  l_valid_mview_count NUMBER;
  l_fresh_mview_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_valid_mview_count
    FROM USER_OBJECTS
   WHERE OBJECT_NAME IN (
     'MARITIME_SS_E_VOYAGE_VESSEL_MV', 'MARITIME_SS_E_VOYAGE_CALL_MV',
     'MARITIME_SS_E_CALL_PORT_MV', 'MARITIME_SS_E_INCIDENT_CALL_MV',
     'MARITIME_SS_E_CARRIED_ON_MV', 'MARITIME_SS_E_CONNECTS_TO_MV',
     'MARITIME_SS_E_INCIDENT_CONTAINER_MV'
   )
     AND OBJECT_TYPE = 'MATERIALIZED VIEW'
     AND STATUS = 'VALID';

  SELECT COUNT(*)
    INTO l_fresh_mview_count
    FROM USER_MVIEWS
   WHERE MVIEW_NAME IN (
     'MARITIME_SS_E_VOYAGE_VESSEL_MV', 'MARITIME_SS_E_VOYAGE_CALL_MV',
     'MARITIME_SS_E_CALL_PORT_MV', 'MARITIME_SS_E_INCIDENT_CALL_MV',
     'MARITIME_SS_E_CARRIED_ON_MV', 'MARITIME_SS_E_CONNECTS_TO_MV',
     'MARITIME_SS_E_INCIDENT_CONTAINER_MV'
   )
     AND STALENESS = 'FRESH'
     AND COMPILE_STATE = 'VALID';

  IF l_valid_mview_count <> 7 OR l_fresh_mview_count <> 7 THEN
    RAISE_APPLICATION_ERROR(
      -20319,
      'Property Graph snapshot precondition failed: valid_mviews=' ||
      l_valid_mview_count || ', fresh_valid_mviews=' || l_fresh_mview_count
    );
  END IF;

  DBMS_OUTPUT.PUT_LINE('PASS MARITIME_SS Property Graph snapshot precondition');
END;
/

CREATE OR REPLACE PROPERTY GRAPH MARITIME_DEMO.MARITIME_SS_SHIP_SHORE_G
  VERTEX TABLES (
    MARITIME_DEMO.MARITIME_SS_INCIDENTS AS MARITIME_SS_INCIDENTS
      KEY (INCIDENT_ID)
      LABEL DELAY_INCIDENT PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_VESSELS AS MARITIME_SS_VESSELS
      KEY (VESSEL_ID)
      LABEL VESSEL PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_VOYAGES AS MARITIME_SS_VOYAGES
      KEY (VOYAGE_ID)
      LABEL VOYAGE PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_PORTS AS MARITIME_SS_PORTS
      KEY (PORT_CODE)
      LABEL PORT PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_PORT_CALLS AS MARITIME_SS_PORT_CALLS
      KEY (PORT_CALL_ID)
      LABEL PORT_CALL PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_BOOKINGS AS MARITIME_SS_BOOKINGS
      KEY (BOOKING_ID)
      LABEL BOOKING PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_CONTAINERS AS MARITIME_SS_CONTAINERS
      KEY (CONTAINER_ID)
      LABEL SHIPPING_CONTAINER PROPERTIES ARE ALL COLUMNS
  )
  EDGE TABLES (
    MARITIME_DEMO.MARITIME_SS_E_INCIDENT_CALL_MV AS MARITIME_SS_E_INCIDENT_CALL_V
      KEY (EDGE_ID)
      SOURCE KEY (INCIDENT_ID) REFERENCES MARITIME_SS_INCIDENTS (INCIDENT_ID)
      DESTINATION KEY (PORT_CALL_ID) REFERENCES MARITIME_SS_PORT_CALLS (PORT_CALL_ID)
      LABEL AFFECTS_PORT_CALL PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_E_VOYAGE_CALL_MV AS MARITIME_SS_E_VOYAGE_CALL_V
      KEY (EDGE_ID)
      SOURCE KEY (VOYAGE_ID) REFERENCES MARITIME_SS_VOYAGES (VOYAGE_ID)
      DESTINATION KEY (PORT_CALL_ID) REFERENCES MARITIME_SS_PORT_CALLS (PORT_CALL_ID)
      LABEL CALLS_AT PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_E_CALL_PORT_MV AS MARITIME_SS_E_CALL_PORT_V
      KEY (EDGE_ID)
      SOURCE KEY (PORT_CALL_ID) REFERENCES MARITIME_SS_PORT_CALLS (PORT_CALL_ID)
      DESTINATION KEY (PORT_CODE) REFERENCES MARITIME_SS_PORTS (PORT_CODE)
      LABEL LOCATED_AT PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_E_VOYAGE_VESSEL_MV AS MARITIME_SS_E_VOYAGE_VESSEL_V
      KEY (EDGE_ID)
      SOURCE KEY (VOYAGE_ID) REFERENCES MARITIME_SS_VOYAGES (VOYAGE_ID)
      DESTINATION KEY (VESSEL_ID) REFERENCES MARITIME_SS_VESSELS (VESSEL_ID)
      LABEL OPERATED_BY PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_BOOKING_CONTAINERS AS MARITIME_SS_BOOKING_CONTAINERS
      KEY (EDGE_ID)
      SOURCE KEY (BOOKING_ID) REFERENCES MARITIME_SS_BOOKINGS (BOOKING_ID)
      DESTINATION KEY (CONTAINER_ID) REFERENCES MARITIME_SS_CONTAINERS (CONTAINER_ID)
      LABEL CONTAINS_CONTAINER PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_E_CARRIED_ON_MV AS MARITIME_SS_E_CARRIED_ON_V
      KEY (EDGE_ID)
      SOURCE KEY (CONTAINER_ID) REFERENCES MARITIME_SS_CONTAINERS (CONTAINER_ID)
      DESTINATION KEY (INBOUND_VOYAGE_ID) REFERENCES MARITIME_SS_VOYAGES (VOYAGE_ID)
      LABEL CARRIED_ON PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_E_CONNECTS_TO_MV AS MARITIME_SS_E_CONNECTS_TO_V
      KEY (EDGE_ID)
      SOURCE KEY (CONTAINER_ID) REFERENCES MARITIME_SS_CONTAINERS (CONTAINER_ID)
      DESTINATION KEY (OUTBOUND_VOYAGE_ID) REFERENCES MARITIME_SS_VOYAGES (VOYAGE_ID)
      LABEL CONNECTS_TO PROPERTIES ARE ALL COLUMNS,
    MARITIME_DEMO.MARITIME_SS_E_INCIDENT_CONTAINER_MV AS MARITIME_SS_E_INCIDENT_CONTAINER_V
      KEY (EDGE_ID)
      SOURCE KEY (INCIDENT_ID) REFERENCES MARITIME_SS_INCIDENTS (INCIDENT_ID)
      DESTINATION KEY (CONTAINER_ID) REFERENCES MARITIME_SS_CONTAINERS (CONTAINER_ID)
      LABEL AFFECTS_CONTAINER PROPERTIES ARE ALL COLUMNS
  )
  OPTIONS (TRUSTED MODE);

DECLARE
  l_valid_graph_count NUMBER;
BEGIN
  SELECT COUNT(*)
    INTO l_valid_graph_count
    FROM USER_OBJECTS
   WHERE OBJECT_NAME = 'MARITIME_SS_SHIP_SHORE_G'
     AND OBJECT_TYPE = 'PROPERTY GRAPH'
     AND STATUS = 'VALID';

  IF l_valid_graph_count <> 1 THEN
    RAISE_APPLICATION_ERROR(
      -20320,
      'Property Graph postcondition failed: valid_graphs=' || l_valid_graph_count
    );
  END IF;

  DBMS_OUTPUT.PUT_LINE('PASS MARITIME_SS Property Graph created and valid');
END;
/

SELECT
  OBJECT_NAME AS GRAPH_NAME,
  OBJECT_TYPE,
  STATUS
FROM USER_OBJECTS
WHERE OBJECT_NAME = 'MARITIME_SS_SHIP_SHORE_G'
  AND OBJECT_TYPE = 'PROPERTY GRAPH'
  AND STATUS = 'VALID';
