-- Maritime Actionable Ontology Demo Kit
-- Stable read-only contracts for deterministic ledger replay and connection decisions.

SET SERVEROUTPUT ON

DECLARE
  l_user   VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'SESSION_USER'));
  l_schema VARCHAR2(128) := UPPER(SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA'));
BEGIN
  IF l_user <> 'MARITIME_DEMO' OR l_schema <> 'MARITIME_DEMO' THEN
    RAISE_APPLICATION_ERROR(-20000, 'Safety stop: connect directly as MARITIME_DEMO.');
  END IF;
END;
/

CREATE OR REPLACE VIEW MARITIME_DEMO.MARITIME_SS_CONTEXT_V AS
SELECT
  m.FIXTURE_VERSION,
  m.CONTRACT_VERSION,
  m.ONTOLOGY_VERSION,
  m.POLICY_VERSION,
  m.SCENARIO_ID,
  m.DATA_AS_OF_TS,
  c.TIMEZONE_REGION,
  p.EFFECTIVE_FROM_TS AS POLICY_EFFECTIVE_FROM_TS,
  p.TIGHT_THRESHOLD_MIN,
  p.MAX_INGEST_LAG_MIN,
  p.APPROVAL_STATE,
  p.EXTERNAL_EXECUTION_YN,
  'SYNTHETIC_DEMO' AS RUN_MODE,
  'SYNTHETIC_FIXTURE' AS RESULT_PROVENANCE,
  m.DATA_SCOPE
FROM MARITIME_DEMO.MARITIME_SS_FIXTURE_MANIFEST m
JOIN MARITIME_DEMO.MARITIME_SS_DEMO_CLOCK c
  ON c.CLOCK_ID = 1
 AND c.AS_OF_TS = m.DATA_AS_OF_TS
 AND c.DATA_SCOPE = m.DATA_SCOPE
JOIN MARITIME_DEMO.MARITIME_SS_POLICY_VERSIONS p
  ON p.POLICY_VERSION = m.POLICY_VERSION
 AND p.ACTIVE_YN = 'Y'
 AND p.EFFECTIVE_FROM_TS <= m.DATA_AS_OF_TS
 AND p.DATA_SCOPE = m.DATA_SCOPE
WHERE m.FIXTURE_VERSION = 'MARITIME-AO-FIXTURE-0.1.0'
  AND m.SCENARIO_ID = 'INC-MAR-0001';

CREATE OR REPLACE VIEW MARITIME_DEMO.MARITIME_SS_LATEST_ETA_V AS
WITH admissible AS (
  SELECT
    e.*,
    ctx.FIXTURE_VERSION,
    ctx.CONTRACT_VERSION,
    ctx.ONTOLOGY_VERSION,
    ctx.POLICY_VERSION,
    ctx.SCENARIO_ID,
    ctx.DATA_AS_OF_TS,
    ctx.TIGHT_THRESHOLD_MIN,
    ctx.MAX_INGEST_LAG_MIN,
    ctx.APPROVAL_STATE,
    ctx.EXTERNAL_EXECUTION_YN,
    ctx.RUN_MODE,
    ctx.RESULT_PROVENANCE,
    LEAD(e.REPORTED_ETA_AT) OVER (
      PARTITION BY e.PORT_CALL_ID
      ORDER BY e.REVISION_NO DESC, e.SOURCE_EVENT_AT DESC, e.ETA_EVENT_ID
    ) AS PRIOR_REPORTED_ETA_AT,
    ROW_NUMBER() OVER (
      PARTITION BY e.PORT_CALL_ID
      ORDER BY e.REVISION_NO DESC, e.SOURCE_EVENT_AT DESC, e.ETA_EVENT_ID
    ) AS RN
  FROM MARITIME_DEMO.MARITIME_SS_ETA_EVENTS e
  CROSS JOIN MARITIME_DEMO.MARITIME_SS_CONTEXT_V ctx
  JOIN MARITIME_DEMO.MARITIME_SS_INCIDENTS root_incident
    ON root_incident.INCIDENT_ID = ctx.SCENARIO_ID
   AND root_incident.PORT_CALL_ID = e.PORT_CALL_ID
  WHERE e.RECEIVED_AT <= ctx.DATA_AS_OF_TS
    AND e.PAYLOAD_STATUS IN ('ACCEPTED', 'CONTROL')
    AND e.DATA_SCOPE = ctx.DATA_SCOPE
)
SELECT
  ETA_EVENT_ID,
  PORT_CALL_ID,
  REVISION_NO,
  SOURCE_SYSTEM,
  SOURCE_EVENT_AT,
  RECEIVED_AT,
  REPORTED_ETA_AT,
  PRIOR_REPORTED_ETA_AT,
  PAYLOAD_STATUS,
  FIXTURE_VERSION,
  CONTRACT_VERSION,
  ONTOLOGY_VERSION,
  POLICY_VERSION,
  SCENARIO_ID,
  DATA_AS_OF_TS,
  TIGHT_THRESHOLD_MIN,
  MAX_INGEST_LAG_MIN,
  APPROVAL_STATE,
  EXTERNAL_EXECUTION_YN,
  RUN_MODE,
  RESULT_PROVENANCE,
  DATA_SCOPE
FROM admissible
WHERE RN = 1;

CREATE OR REPLACE VIEW MARITIME_DEMO.MARITIME_SS_INGEST_HEALTH_V AS
WITH event_counts AS (
  SELECT
    e.PORT_CALL_ID,
    SUM(CASE WHEN e.RECEIVED_AT <= ctx.DATA_AS_OF_TS THEN 1 ELSE 0 END)
      AS ADMITTED_EVENT_COUNT,
    SUM(CASE WHEN e.RECEIVED_AT > ctx.DATA_AS_OF_TS THEN 1 ELSE 0 END)
      AS FUTURE_EVENT_EXCLUDED_COUNT
  FROM MARITIME_DEMO.MARITIME_SS_ETA_EVENTS e
  CROSS JOIN MARITIME_DEMO.MARITIME_SS_CONTEXT_V ctx
  JOIN MARITIME_DEMO.MARITIME_SS_INCIDENTS root_incident
    ON root_incident.INCIDENT_ID = ctx.SCENARIO_ID
   AND root_incident.PORT_CALL_ID = e.PORT_CALL_ID
  WHERE e.PAYLOAD_STATUS IN ('ACCEPTED', 'CONTROL')
    AND e.DATA_SCOPE = ctx.DATA_SCOPE
  GROUP BY e.PORT_CALL_ID
),
out_of_order AS (
  SELECT
    e.PORT_CALL_ID,
    COUNT(*) AS OUT_OF_ORDER_EVENT_COUNT
  FROM MARITIME_DEMO.MARITIME_SS_ETA_EVENTS e
  CROSS JOIN MARITIME_DEMO.MARITIME_SS_CONTEXT_V ctx
  JOIN MARITIME_DEMO.MARITIME_SS_INCIDENTS root_incident
    ON root_incident.INCIDENT_ID = ctx.SCENARIO_ID
   AND root_incident.PORT_CALL_ID = e.PORT_CALL_ID
  WHERE e.RECEIVED_AT <= ctx.DATA_AS_OF_TS
    AND e.PAYLOAD_STATUS IN ('ACCEPTED', 'CONTROL')
    AND EXISTS (
      SELECT 1
      FROM MARITIME_DEMO.MARITIME_SS_ETA_EVENTS newer
      WHERE newer.PORT_CALL_ID = e.PORT_CALL_ID
        AND newer.REVISION_NO > e.REVISION_NO
        AND newer.RECEIVED_AT < e.RECEIVED_AT
        AND newer.RECEIVED_AT <= ctx.DATA_AS_OF_TS
        AND newer.PAYLOAD_STATUS IN ('ACCEPTED', 'CONTROL')
    )
  GROUP BY e.PORT_CALL_ID
)
SELECT
  pc.PORT_CALL_ID,
  pc.VOYAGE_ID,
  pc.PORT_CODE,
  pc.TERMINAL_CODE,
  latest.ETA_EVENT_ID AS SELECTED_ETA_EVENT_ID,
  latest.REVISION_NO AS SELECTED_REVISION_NO,
  pc.PLANNED_ARRIVAL_AT,
  latest.PRIOR_REPORTED_ETA_AT,
  latest.REPORTED_ETA_AT AS SELECTED_ETA_AT,
  latest.SOURCE_EVENT_AT,
  latest.RECEIVED_AT,
  ROUND(
    (
      CAST(SYS_EXTRACT_UTC(latest.RECEIVED_AT) AS DATE)
      - CAST(SYS_EXTRACT_UTC(latest.SOURCE_EVENT_AT) AS DATE)
    ) * 1440
  ) AS INGEST_LAG_MINUTES,
  ROUND(
    (
      CAST(SYS_EXTRACT_UTC(latest.REPORTED_ETA_AT) AS DATE)
      - CAST(SYS_EXTRACT_UTC(latest.PRIOR_REPORTED_ETA_AT) AS DATE)
    ) * 1440
  ) AS ETA_REVISION_DELTA_MINUTES,
  ROUND(
    (
      CAST(SYS_EXTRACT_UTC(latest.REPORTED_ETA_AT) AS DATE)
      - CAST(SYS_EXTRACT_UTC(pc.PLANNED_ARRIVAL_AT) AS DATE)
    ) * 1440
  ) AS SCHEDULE_VARIANCE_MINUTES,
  ec.ADMITTED_EVENT_COUNT,
  ec.FUTURE_EVENT_EXCLUDED_COUNT,
  NVL(ooo.OUT_OF_ORDER_EVENT_COUNT, 0) AS OUT_OF_ORDER_EVENT_COUNT,
  latest.MAX_INGEST_LAG_MIN,
  CASE
    WHEN latest.RECEIVED_AT
           > latest.SOURCE_EVENT_AT
             + NUMTODSINTERVAL(latest.MAX_INGEST_LAG_MIN, 'MINUTE')
      THEN 'LAG_EXCEEDED'
    WHEN NVL(ooo.OUT_OF_ORDER_EVENT_COUNT, 0) > 0
      THEN 'ACCEPTED_WITH_LATE_EVENT'
    ELSE 'ON_TIME'
  END AS INGEST_STATUS,
  latest.FIXTURE_VERSION,
  latest.CONTRACT_VERSION,
  latest.ONTOLOGY_VERSION,
  latest.POLICY_VERSION,
  latest.SCENARIO_ID AS CONTEXT_SCENARIO_ID,
  latest.DATA_AS_OF_TS,
  latest.RUN_MODE,
  latest.RESULT_PROVENANCE,
  latest.APPROVAL_STATE,
  latest.EXTERNAL_EXECUTION_YN,
  latest.DATA_SCOPE
FROM MARITIME_DEMO.MARITIME_SS_PORT_CALLS pc
JOIN MARITIME_DEMO.MARITIME_SS_LATEST_ETA_V latest
  ON latest.PORT_CALL_ID = pc.PORT_CALL_ID
JOIN event_counts ec
  ON ec.PORT_CALL_ID = pc.PORT_CALL_ID
LEFT JOIN out_of_order ooo
  ON ooo.PORT_CALL_ID = pc.PORT_CALL_ID;

CREATE OR REPLACE VIEW MARITIME_DEMO.MARITIME_SS_CONNECTION_DECISION_V AS
WITH inputs AS (
  SELECT
    i.INCIDENT_ID,
    i.INCIDENT_STATUS,
    i.SEVERITY,
    i.RECORDED_DELAY_MIN,
    c.CONNECTION_ID,
    c.INBOUND_VOYAGE_ID,
    c.OUTBOUND_VOYAGE_ID,
    c.PORT_CALL_ID,
    c.CONTAINER_ID,
    bc.BOOKING_ID,
    b.BOOKING_NO,
    b.CUSTOMER_PRIORITY,
    b.CARGO_CATEGORY,
    ctr.CONTAINER_NO,
    ctr.ISO_TYPE,
    ctr.REEFER_YN,
    ctr.DANGEROUS_GOODS_YN,
    ctr.PRIORITY_CODE,
    latest.ETA_EVENT_ID AS SELECTED_ETA_EVENT_ID,
    latest.REVISION_NO AS SELECTED_REVISION_NO,
    latest.REPORTED_ETA_AT AS SELECTED_ETA_AT,
    latest.SOURCE_EVENT_AT AS SELECTED_SOURCE_EVENT_AT,
    latest.RECEIVED_AT AS SELECTED_RECEIVED_AT,
    c.PLANNED_READY_OFFSET_MIN,
    latest.REPORTED_ETA_AT
      + NUMTODSINTERVAL(c.PLANNED_READY_OFFSET_MIN, 'MINUTE')
      AS ESTIMATED_READY_AT,
    cutoff.LOAD_CUTOFF_AT,
    latest.FIXTURE_VERSION,
    latest.CONTRACT_VERSION,
    latest.ONTOLOGY_VERSION,
    latest.POLICY_VERSION,
    latest.SCENARIO_ID AS CONTEXT_SCENARIO_ID,
    latest.DATA_AS_OF_TS,
    latest.TIGHT_THRESHOLD_MIN,
    latest.APPROVAL_STATE,
    latest.EXTERNAL_EXECUTION_YN,
    latest.RUN_MODE,
    latest.RESULT_PROVENANCE,
    c.DATA_SCOPE
  FROM MARITIME_DEMO.MARITIME_SS_INCIDENTS i
  JOIN MARITIME_DEMO.MARITIME_SS_CONNECTIONS c
    ON c.PORT_CALL_ID = i.PORT_CALL_ID
  JOIN MARITIME_DEMO.MARITIME_SS_LATEST_ETA_V latest
    ON latest.PORT_CALL_ID = c.PORT_CALL_ID
  JOIN MARITIME_DEMO.MARITIME_SS_TERMINAL_CUTOFFS cutoff
    ON cutoff.PORT_CALL_ID = c.PORT_CALL_ID
   AND cutoff.OUTBOUND_VOYAGE_ID = c.OUTBOUND_VOYAGE_ID
  JOIN MARITIME_DEMO.MARITIME_SS_CONTAINERS ctr
    ON ctr.CONTAINER_ID = c.CONTAINER_ID
  JOIN MARITIME_DEMO.MARITIME_SS_BOOKING_CONTAINERS bc
    ON bc.CONTAINER_ID = c.CONTAINER_ID
  JOIN MARITIME_DEMO.MARITIME_SS_BOOKINGS b
    ON b.BOOKING_ID = bc.BOOKING_ID
  JOIN MARITIME_DEMO.MARITIME_SS_VOYAGES inbound_voyage
    ON inbound_voyage.VOYAGE_ID = c.INBOUND_VOYAGE_ID
  JOIN MARITIME_DEMO.MARITIME_SS_VOYAGES outbound_voyage
    ON outbound_voyage.VOYAGE_ID = c.OUTBOUND_VOYAGE_ID
  WHERE i.INCIDENT_STATUS = 'OPEN'
    AND i.INCIDENT_ID = latest.SCENARIO_ID
    AND latest.PAYLOAD_STATUS = 'ACCEPTED'
    AND c.CONNECTION_STATE = 'PLANNED'
    AND b.BOOKING_STATUS = 'CONFIRMED'
    AND inbound_voyage.VOYAGE_ROLE = 'INBOUND'
    AND inbound_voyage.VOYAGE_STATUS = 'IN_PROGRESS'
    AND outbound_voyage.VOYAGE_ROLE = 'OUTBOUND'
    AND outbound_voyage.VOYAGE_STATUS = 'PLANNED'
),
calculated AS (
  SELECT
    inputs.*,
    ROUND(
      (
        CAST(SYS_EXTRACT_UTC(LOAD_CUTOFF_AT) AS DATE)
        - CAST(SYS_EXTRACT_UTC(ESTIMATED_READY_AT) AS DATE)
      ) * 1440
    ) AS CONNECTION_SLACK_MINUTES,
    ROUND(
      (
        CAST(SYS_EXTRACT_UTC(LOAD_CUTOFF_AT) AS DATE)
        - CAST(SYS_EXTRACT_UTC(ESTIMATED_READY_AT) AS DATE)
      ) * 86400
    ) AS CONNECTION_SLACK_SECONDS
  FROM inputs
)
SELECT
  calculated.*,
  CASE
    WHEN ESTIMATED_READY_AT > LOAD_CUTOFF_AT THEN 'MISS'
    WHEN ESTIMATED_READY_AT
           > LOAD_CUTOFF_AT - NUMTODSINTERVAL(TIGHT_THRESHOLD_MIN, 'MINUTE')
      THEN 'TIGHT'
    ELSE 'KEEP'
  END AS DECISION_CODE,
  CASE
    WHEN ESTIMATED_READY_AT > LOAD_CUTOFF_AT
      THEN '다음 운항편 연결이 어려운 규칙 분류'
    WHEN ESTIMATED_READY_AT
           > LOAD_CUTOFF_AT - NUMTODSINTERVAL(TIGHT_THRESHOLD_MIN, 'MINUTE')
      THEN '적재 마감까지 여유가 제한적인 규칙 분류'
    ELSE '현재 계획 유지가 가능한 규칙 분류'
  END AS DECISION_REASON
FROM calculated;

CREATE OR REPLACE VIEW MARITIME_DEMO.MARITIME_SS_SEMANTIC_INPUT_V AS
SELECT
  INCIDENT_ID,
  CONNECTION_ID,
  INBOUND_VOYAGE_ID,
  OUTBOUND_VOYAGE_ID,
  PORT_CALL_ID,
  CONTAINER_ID,
  CONTAINER_NO,
  BOOKING_ID,
  BOOKING_NO,
  CUSTOMER_PRIORITY,
  CARGO_CATEGORY,
  ISO_TYPE,
  REEFER_YN,
  DANGEROUS_GOODS_YN,
  PRIORITY_CODE,
  SELECTED_ETA_EVENT_ID,
  SELECTED_REVISION_NO,
  SELECTED_ETA_AT,
  SELECTED_SOURCE_EVENT_AT,
  SELECTED_RECEIVED_AT,
  PLANNED_READY_OFFSET_MIN,
  ESTIMATED_READY_AT,
  LOAD_CUTOFF_AT,
  CONNECTION_SLACK_MINUTES,
  CONNECTION_SLACK_SECONDS,
  DECISION_CODE,
  DECISION_REASON,
  FIXTURE_VERSION,
  CONTRACT_VERSION,
  ONTOLOGY_VERSION,
  POLICY_VERSION,
  CONTEXT_SCENARIO_ID,
  DATA_AS_OF_TS,
  TIGHT_THRESHOLD_MIN,
  RUN_MODE,
  RESULT_PROVENANCE,
  APPROVAL_STATE,
  EXTERNAL_EXECUTION_YN,
  DATA_SCOPE
FROM MARITIME_DEMO.MARITIME_SS_CONNECTION_DECISION_V;

CREATE OR REPLACE VIEW MARITIME_DEMO.MARITIME_SS_EXECUTIVE_V AS
SELECT
  d.INCIDENT_ID,
  d.INBOUND_VOYAGE_ID,
  d.PORT_CALL_ID,
  MAX(h.SELECTED_ETA_EVENT_ID) AS SELECTED_ETA_EVENT_ID,
  MAX(h.SELECTED_REVISION_NO) AS SELECTED_REVISION_NO,
  MAX(h.SELECTED_ETA_AT) AS SELECTED_ETA_AT,
  MAX(h.PRIOR_REPORTED_ETA_AT) AS PRIOR_REPORTED_ETA_AT,
  MAX(h.ETA_REVISION_DELTA_MINUTES) AS ETA_REVISION_DELTA_MINUTES,
  MAX(h.SCHEDULE_VARIANCE_MINUTES) AS SCHEDULE_VARIANCE_MINUTES,
  MAX(h.SOURCE_EVENT_AT) AS SELECTED_SOURCE_EVENT_AT,
  MAX(h.RECEIVED_AT) AS SELECTED_RECEIVED_AT,
  MAX(h.INGEST_LAG_MINUTES) AS INGEST_LAG_MINUTES,
  MAX(h.ADMITTED_EVENT_COUNT) AS ADMITTED_EVENT_COUNT,
  MAX(h.FUTURE_EVENT_EXCLUDED_COUNT) AS FUTURE_EVENT_EXCLUDED_COUNT,
  MAX(h.OUT_OF_ORDER_EVENT_COUNT) AS OUT_OF_ORDER_EVENT_COUNT,
  MAX(h.INGEST_STATUS) AS INGEST_STATUS,
  COUNT(*) AS ASSESSED_CONNECTION_COUNT,
  COUNT(DISTINCT d.CONTAINER_ID) AS CONTAINER_COUNT,
  COUNT(DISTINCT d.BOOKING_ID) AS BOOKING_COUNT,
  SUM(CASE WHEN d.DECISION_CODE = 'MISS' THEN 1 ELSE 0 END) AS MISS_COUNT,
  SUM(CASE WHEN d.DECISION_CODE = 'TIGHT' THEN 1 ELSE 0 END) AS TIGHT_COUNT,
  SUM(CASE WHEN d.DECISION_CODE = 'KEEP' THEN 1 ELSE 0 END) AS KEEP_COUNT,
  MAX(d.FIXTURE_VERSION) AS FIXTURE_VERSION,
  MAX(d.CONTRACT_VERSION) AS CONTRACT_VERSION,
  MAX(d.ONTOLOGY_VERSION) AS ONTOLOGY_VERSION,
  d.POLICY_VERSION,
  MAX(d.CONTEXT_SCENARIO_ID) AS CONTEXT_SCENARIO_ID,
  MAX(d.DATA_AS_OF_TS) AS DATA_AS_OF_TS,
  MAX(d.TIGHT_THRESHOLD_MIN) AS TIGHT_THRESHOLD_MIN,
  MAX(d.RUN_MODE) AS RUN_MODE,
  MAX(d.RESULT_PROVENANCE) AS RESULT_PROVENANCE,
  MAX(d.APPROVAL_STATE) AS APPROVAL_STATE,
  MAX(d.EXTERNAL_EXECUTION_YN) AS EXTERNAL_EXECUTION_YN,
  MAX(d.DATA_SCOPE) AS DATA_SCOPE
FROM MARITIME_DEMO.MARITIME_SS_CONNECTION_DECISION_V d
JOIN MARITIME_DEMO.MARITIME_SS_INGEST_HEALTH_V h
  ON h.PORT_CALL_ID = d.PORT_CALL_ID
 AND h.POLICY_VERSION = d.POLICY_VERSION
 AND h.FIXTURE_VERSION = d.FIXTURE_VERSION
GROUP BY
  d.INCIDENT_ID,
  d.INBOUND_VOYAGE_ID,
  d.PORT_CALL_ID,
  d.POLICY_VERSION;

COMMENT ON TABLE MARITIME_DEMO.MARITIME_SS_CONTEXT_V IS
  'Singleton synthetic demo provenance and manifest-bound policy context for deterministic replay.';
COMMENT ON TABLE MARITIME_DEMO.MARITIME_SS_LATEST_ETA_V IS
  'Latest admissible ETA for the manifest scenario port call at DATA_AS_OF_TS, selected by revision rather than receive order.';
COMMENT ON TABLE MARITIME_DEMO.MARITIME_SS_INGEST_HEALTH_V IS
  'Ledger replay quality, as-of selection, revision delta, schedule variance, and late-event evidence.';
COMMENT ON TABLE MARITIME_DEMO.MARITIME_SS_CONNECTION_DECISION_V IS
  'One row per eligible incident-scoped container connection with timestamps, slack, and manifest-bound policy result.';
COMMENT ON TABLE MARITIME_DEMO.MARITIME_SS_SEMANTIC_INPUT_V IS
  'Stable decision-support contract: one row per eligible assessed container connection with synthetic demo provenance.';
COMMENT ON TABLE MARITIME_DEMO.MARITIME_SS_EXECUTIVE_V IS
  'Single synthetic-demo summary: revision delta +420, schedule variance +420, 36 decisions, 9/6/21.';
COMMENT ON COLUMN MARITIME_DEMO.MARITIME_SS_CONNECTION_DECISION_V.CONNECTION_SLACK_MINUTES IS
  'Rounded display value: terminal cutoff minus estimated ready time. Timestamp instants, not this rounded value, drive classification.';
COMMENT ON COLUMN MARITIME_DEMO.MARITIME_SS_CONNECTION_DECISION_V.DECISION_CODE IS
  'Closed-world policy result. MISS is not proof that a transshipment failure has completed.';

SELECT 'PASS MARITIME_SS deterministic decision contracts created' AS STATUS
FROM DUAL;
